alias wc = uu-wc
alias chown = uu-chown
alias chmod = uu-chmod
alias date = uu-date
alias mv = uu-mv
alias cp = uu-cp
alias head = uu-head
alias tail = uu-tail
alias rm = uu-rm
alias pwd = uu-pwd
alias more = uu-more
alias mkdir = uu-mkdir
# alias du = uu-du
alias df = uu-df
alias kill = uu-kill
alias sleep = uu-sleep
alias touch = uu-touch
alias uname = uu-uname