# App shortcuts
# bind=SUPER,slash,spawn,bitwarden

# bind=SUPER,c,spawn,cursor
# bind=SUPER,f,spawn,nautilus
# bind=SUPER+SHIFT,f,spawn,foot -T SPF spf
# bind=SUPER,h,spawn,foot -T HTOP htop
# bind=SUPER,l,spawn,foot -T LAZYGIT lazygit
# bind=SUPER,m,spawn,spotify
# bind=SUPER+CTRL,n,spawn,foot -T IMPALA impala
# bind=SUPER,n,spawn,foot -T NEOVIM nvim
# bind=SUPER,o,spawn,obsidian
# bind=SUPER,t,spawn,chromium
# bind=SUPER,x,spawn,foot claude
