# Cycle through layouts
bind=SUPER+CTRL,n,switch_layout

# Set specific layout
bind=SUPER+CTRL,t,setlayout,tile
bind=SUPER+CTRL,s,setlayout,scroller
bind=SUPER+CTRL,c,setlayout,center_tile
bind=SUPER+CTRL,d,setlayout,dwindle
