# Layout control
bind=SUPER+ALT,n,switch_layout,

# Layouts
bind=SUPER+CTRL,t,spawn,mmsg -l "T"  # tiling
bind=SUPER+CTRL,x,spawn,mmsg -l "TG"  # tgmix
bind=SUPER+CTRL,m,spawn,mmsg -l "M"  # monocle
bind=SUPER+CTRL,g,spawn,mmsg -l "G"  # grid
bind=SUPER+CTRL,d,spawn,mmsg -l "K"  # deck
bind=SUPER+CTRL,c,spawn,mmsg -l "CT" # centerTiling
bind=SUPER+CTRL,v,spawn,mmsg -l "VT" # verticalTiling
bind=SUPER+CTRL,s,spawn,mmsg -l "S"  # scrolling
bind=SUPER+CTRL,e,spawn,mmsg -l "VS" # verticalScrolling

# Master/stack control
bind=SUPER+ALT,e,incnmaster,1
bind=SUPER+ALT,t,incnmaster,-1
bind=SUPER+ALT,h,setmfact,-0.05
bind=SUPER+ALT,l,setmfact,+0.05

# Proportion control (SCROLLER)
bind=SUPER+SHIFT,e,set_proportion,0.33
bind=SUPER+ALT,x,switch_proportion_preset,

# Scroller Stacking
bind=SUPER+ALT,Left,scroller_stack,left
bind=SUPER+ALT,Up,scroller_stack,up
bind=SUPER+ALT,Down,scroller_stack,down
bind=SUPER+ALT,Right,scroller_stack,right
