# monitor focus
# bind=super+alt,left,focusmon,left
bind=super,o,focusmon,right
# bind=super+alt,up,focusmon,up
# bind=super+alt,down,focusmon,down

# move to monitor
# bind=super+alt+shift,left,tagmon,left
bind=super+shift,o,tagmon,right
# bind=super+alt+shift,up,tagmon,up
# bind=super+alt+shift,down,tagmon,down
