# Wofi launchers and menus
bind=CTRL+SUPER,d,spawn,rofi -show run
bind=SUPER+SHIFT,d,spawn,kickoff
bind=SUPER,v,spawn,/home/cirno99/.config/mango/rofi-clip

# Waybar toggle
bind=SUPER+SHIFT,b,spawn_shell,~/.local/bin/toggle-waybar
bind=SUPER+ALT,b,spawn_shell,~/.local/bin/restart-waybar
bind=SUPER+SHIFT,t,spawn,~/.local/bin/wofi-theme-switcher

# Change Wallpaper
bind=SUPER+SHIFT,n,spawn,/home/cirno99/.config/mango/change_wallpaper.sh


# Power menu
bind=SUPER,x,spawn,wlogout

# Wallpaper management
bind=SUPER+ALT,w,spawn,unified-wallpaper
bind=SUPER+ALT,p,spawn,unified-wallpaper --prev
bind=SUPER+ALT+SHIFT,w,spawn,unified-wallpaper --random
bind=CTRL+ALT+SHIFT,t,spawn,unified-wallpaper --time

# Screenshots
bind=None,Print,spawn,grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
bind=SUPER,e,spawn,/home/cirno99/.config/mango/grim-cli select-copy
bind=SUPER+SHIFT,e,spawn,/home/cirno99/.config/mango/grim-cli copy
