exec-once=$HOME/.config/mango/autostart.sh
# exec-once=pipewire
# exec-once=pipewire-pulse
# exec-once=wireplumber
exec-once=vibepanel
# exec-once=dms run
# exec-once=kanshi
exec-once=foot -s
exec-once=fcitx5
exec-once=wl-paste --type text --watch clipvault store
exec-once=wl-paste --type image --watch clipvault store 
exec-once=xrdb -merge ~/.Xresources
exec-once=swaybg -i /home/cirno99/backup/wallpapers/pixiv/2020/PID=84368199_四_UID=19389056_p0.jpg -m fill
# exec-once=swayosd-server
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/lib/xdg-desktop-portal-termfilechooser
