# Basic window rules
# windowrule=unfocused_opacity:0.85,focused_opacity:0.95,appid:kitty
# windowrule=unfocused_opacity:0.55,focused_opacity:0.95,appid:foot
# windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:Google-chrome


# windowrule=isfloating:1,title:BTOP,width:1200,height:900,isoverlay:1
# windowrule=isfloating:1,title:BTUI,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:HTOP,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:IMPALA,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:LAZYGIT,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:NEOVIM,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:SPF,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,title:WIREMIX,width:800,height:600,isoverlay:1
# windowrule=isfloating:1,appid:org.gnome.Nautilus,width:1200,height:900,isoverlay:1
