# =============================================================================
# vibepanel Configuration
# =============================================================================
#
# Minimal starter config. For all available options, see:
# https://github.com/prankstr/vibepanel/blob/main/docs/configuration.md
#
# Commands:
#   vibepanel --check-config         Validate configuration
#   vibepanel --print-example-config Print this example config
#
# =============================================================================

[bar]
size = 32
border_radius = 30
background_opacity = 0.0 # 0.0 = transparent (islands), 1.0 = solid

[widgets]
left = ["workspaces", "window_title"]
center = ["media"]
right = [
  "tray",
  "updates",
  "cpu",
  "quick_settings",
  "battery",
  "clock",
  "notifications",
  "custom-power"
]
border_radius = 40
background_opacity = 1.0

[widgets.workspaces]
label_type = "numbers"

[widgets.custom-power]
icon = "system-shutdown-symbolic"
label = ""
tooltip = "Power menu"
on_click = "wlogout"
on_click_right = "systemctl suspend"

[widgets.custom-weather]
exec = "curl -s 'wttr.in/Jieyang?format=1' | sed 's/ //g'"
template = "{output}"
interval = 600
on_click = "xdg-open https://wttr.in"
tooltip = "Weather"
max_chars = 30
show_if = "ping -c1 -W1 1.1.1.1"
show_if_interval = 300

# Per-widget options use [widgets.<name>] sections.
# Example:
#   [widgets.clock]
#   format = "%H:%M"
#
#   [widgets.battery]
#   disabled = true
#
# See documentation for all widget options.

[theme]
mode = "auto" # "auto", "dark", "light", "gtk"
#accent = "#adabe0" # "gtk", "none", or hex color

[theme.icons]
theme = "material" # "material" or "gtk"
weight = 400       # Material icon stroke weight (100-700)

[osd]
enabled = true
position = "bottom" # "bottom", "top", "left", "right"

[advanced]
compositor = "mango"  # "auto", "hyprland", "niri", "mango"


# Custom CSS: place style.css in same directory as this file.
# See documentation for available CSS variables and classes.
